version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - ./testing.env
    ports:
      - '6600:3306'
    volumes:
      - ./data/mysql-testing:/var/lib/mysql
