version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - ./.env
    ports:
      - '6500:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql

  webserver:
    container_name: webserver
    build: docker/webserver
    env_file:
      - ./.env
    volumes:
      - .:/srv/:ro
    ports:
      - '80:8000'
      - '443:8080'
