name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build without admin-api
      run: cargo build --verbose
    - name: Build with admin-api
      run: cargo build --verbose -F "admin-api"
